//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Scrumr.Web.MainSite.ReadModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ScrumboardViewContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ScrumboardViewContainer object using the connection string found in the 'ScrumboardViewContainer' section of the application configuration file.
        /// </summary>
        public ScrumboardViewContainer() : base("name=ScrumboardViewContainer", "ScrumboardViewContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScrumboardViewContainer object.
        /// </summary>
        public ScrumboardViewContainer(string connectionString) : base(connectionString, "ScrumboardViewContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScrumboardViewContainer object.
        /// </summary>
        public ScrumboardViewContainer(EntityConnection connection) : base(connection, "ScrumboardViewContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
